language: c
compiler:
- clang
- gcc
before_install:
  - wget https://gist.github.com/petere/5893799/raw/apt.postgresql.org.sh
  - wget https://gist.github.com/petere/6023944/raw/pg-travis-test.sh
  - sudo sh ./apt.postgresql.org.sh
  - sudo apt-get update
  - sudo apt-get autoremove
  - sudo apt-get install -f
  - sudo apt-get -f install
  - sudo apt-get install -fV libatk-wrapper-java-jni postgresql-client-common libgtk2.0-0 libpq-dev
  - sudo apt-get install -fV --ignore-hold libatk-wrapper-java-jni postgresql-client-common libgtk2.0-0 libpq-dev
env:
  - PGVERSION=9.3
  - PGVERSION=9.4
  - PGVERSION=9.5
  - PGVERSION=9.6
script: bash ./pg-travis-test.sh
