language: c
compiler:
- clang
before_install:
  - wget https://gist.github.com/petere/5893799/raw/apt.postgresql.org.sh
  - wget https://gist.github.com/petere/6023944/raw/pg-travis-test.sh
  - sudo sh ./apt.postgresql.org.sh
  - ls -la /var/lib/apt/lists/apt.postgresql.org*
  - sudo sh -c "echo deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main $PGVERSION >> /etc/apt/sources.list.d/pgdg.list"
  - cat /etc/apt/sources.list.d/pgdg.list
  - sudo apt-cache policy postgresql-$PGVERSION
  - sudo apt-cache policy libpq-dev
  - sudo apt-cache policy libpq-dev=9.5\*
  - apt-cache showpkg libpq-dev
  - sudo sh -c "echo deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg $PGVERSION > /etc/apt/sources.list.d/pgdg.list"
  - sudo apt-get update
  - apt-cache showpkg libpq-dev
  - cat /etc/apt/sources.list.d/pgdg.list
  - sudo apt-cache policy libpq-dev
  - sudo apt-cache policy libpq-dev=9.5.\*
  - sudo apt-get autoremove
  - sudo apt-get install -f
  - sudo apt-get -fV check
  - sudo apt-get install -fV libatk-wrapper-java-jni postgresql-client-common libgtk2.0-0 libpq-dev=9.5\*
  - sudo apt-get install -fV --ignore-hold libatk-wrapper-java-jni postgresql-client-common libgtk2.0-0 libpq-dev=9.5\*
env:
  - PGVERSION=9.4
  - PGVERSION=9.5
script: bash ./pg-travis-test.sh
