language: c
before_install:
  - wget https://gist.github.com/petere/5893799/raw/apt.postgresql.org.sh
  - wget https://gist.github.com/petere/6023944/raw/pg-travis-test.sh
  - sudo sh ./apt.postgresql.org.sh
  - sudo apt-get update
  - sudo apt-get upgrade
env:
  - PGVERSION=9.3
  - PGVERSION=9.4
  - PGVERSION=9.5
  - PGVERSION=9.6
  - PGVERSION=main
script: bash ./pg-travis-test.sh
