language: c
compiler:
  - clang
  - gcc
before_install:
  - wget https://gist.github.com/petere/5893799/raw/apt.postgresql.org.sh
  - wget https://gist.github.com/petere/6023944/raw/pg-travis-test.sh
  - sudo sh ./apt.postgresql.org.sh
  - sudo sh -c "echo deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs 2>/dev/null)-pgdg pool $PGVERSION >> /etc/apt/sources.list.d/pgdg.list"
  - sudo apt-get update
  - cat /etc/apt/sources.list.d/pgdg.list
  - sudo apt-cache policy postgresql-$PGVERSION
  - sudo apt-cache policy libpq-dev
  - apt-cache showpkg libpq-dev
    #  - sudo sh -c "echo deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg $PGVERSION > /etc/apt/sources.list.d/pgdg.list"
  - sudo apt-get update
  - apt-cache showpkg libpq-dev
env:
  - PGVERSION=9.3
  - PGVERSION=9.4
  - PGVERSION=9.5
  - PGVERSION=9.6
script: bash ./pg-travis-test.sh
